### ISSUE TITLE
Error - cannot log events

### ISSUE THREAD

**Issue by couquino** [itsrennyman/aurora#43]
Hi,

there is my logs

`error: update "events" set "duration" = $1 where "id" = $2 and "website_id" = $3 returning * - invalid input syntax for type integer: "null"

    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)

    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)

    at Socket.emit (events.js:315:20)

    at addChunk (internal/streams/readable.js:309:12)

    at readableAddChunk (internal/streams/readable.js:284:9)

    at Socket.Readable.push (internal/streams/readable.js:223:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {

  length: 105,

  severity: 'ERROR',

  code: '22P02',

  detail: undefined,

  hint: undefined,

  position: undefined,

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: undefined,

  table: undefined,

  column: undefined,

  dataType: undefined,

  constraint: undefined,

  file: 'numutils.c',

  line: '256',

  routine: 'pg_strtoint32'

}

error: insert into "locales" ("local", "location", "name", "tag") values ($1, $2, $3, $4) returning * - null value in column "local" violates not-null constraint

    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)

    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)

    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)

    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)

    at Socket.emit (events.js:315:20)

    at addChunk (internal/streams/readable.js:309:12)

    at readableAddChunk (internal/streams/readable.js:284:9)

    at Socket.Readable.push (internal/streams/readable.js:223:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {

  length: 263,

  severity: 'ERROR',

  code: '23502',

  detail: 'Failing row contains (12, French, null, France, fr-FR, 2021-05-14 08:26:23.014617+00, 2021-05-14 08:26:23.014617+00).',

  hint: undefined,

  position: undefined,

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: 'public',

  table: 'locales',

  column: 'local',

  dataType: undefined,

  constraint: undefined,

  file: 'execMain.c',

  line: '1948',

  routine: 'ExecConstraints'

}`

**Comment by itsrennyman** [comment]
Hi!

Please can you tell me what browser & device are you using?

Many thanks.

**Comment by couquino** [comment]
Hello,

I tried to use Brave 1.24.84 Chromium: 90.0.4430.93 (Windows 10 PC) & Safari (iOS 14.5)

**Comment by itsrennyman** [comment]
Thank you, I will check. the problems.

The other tracking operation is working correctly right?

**Comment by couquino** [comment]
Only bots (Google I think) worked so far

**Comment by itsrennyman** [comment]
Checked your problems, I'm making some fix. in the next release will be available.

**Comment by itsrennyman** [comment]
Please @couquino try again with the v0.6.1

**Comment by couquino** [comment]
Yup, it works ! Thanks :)
